name: ${pluginName}
main: com.aleksey.bs.BiomesAndSeasons
version: ${version}
authors: [Aleksey-Terzi]
description: ${description}
api-version: ${api_version}
depend: [RealisticBiomes, RealisticSeasons]